### 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "{{member_email}}",
  "password": "{{password}}"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

###
GET http://{{host}}/test/v2
Accept: application/json

###
GET http://{{host}}/test/v3/99
Accept: application/json

###
POST http://{{host}}/test/v4
Content-Type: application/json

{
  "name": "킹받네",
  "email": "admin@admin.com",
  "password": "Aa12341234!",
  "role": "ROLE_MEMBER",
  "contact": "010-1234-5678"
}

###
GET http://{{host}}/testing
Accept: application/json
